### **Python** Syntax:
---

In this course, we'll mainly focus on NumPy, SciPy, Scikit-learn, Matplotlib and PyTorch.

Some of the functions/operations are native (they come installed with python) while others you'll need to install.

I would recommend using the Anaconda/MiniConda Platform. It is easy to install and manage your installation.

Highly Recommended Practice: Use a Virtual environment to avoid breaking python in your whole OS.

We'll be **exclusively working** with Python 3 Syntax and with Jupyter Notebooks.



Usually at the start of our script, we import all the necessary libraries/packages that we'll use throughout the code.
There exist many many packages in python for almost everything.


In [ ]:
# this is a comment!!
# for this tutorial we only need numpy,
# the as ... syntax is used to create a symbolic abbreviation of the package
# thus afterwards we do not need to write numpy.something but instead np.something
import numpy as np


### **Variable Creation**:
---
In Python, we can define a variable at whatever stage we're at and of any type we want.

In [ ]:
# simple variable creation

# this is a float
x = 2.

# this is a string / str in python
y = 'ml course'

# this denotes a boolean variable
flag = True

# To see the values of the variables, we use the print function
# we'll see the string manipulation inside the print function shortly
print('x has value: %.4f'%x)
print('y has value: %s'%y)

# the empty print, just prints a newline
print()

# for the boolean values, adding not in front, inverts their value: not False = True, not True = False
print('Boolean value: %s'%flag)
print('Boolean inverted: %s'%(not flag))

print()

x has value: 2.0000
y has value: ml course

Boolean value: True
Boolean inverted: False



In [3]:
# If at some point you're uncertain about the variables you are using, you can check their type
print('Type of x: %s'%type(x))
print('Type of y: %s'%type(y))
print('Type of flag: %s'%type(flag))

Type of x: <class 'float'>
Type of y: <class 'str'>
Type of flag: <class 'bool'>


### **Simple Operations with Python Variables**
---
Having defined some variables, we can perform several operations on them.
We can add/subtract/multiply/divide integer/floats, use modulo, perform integer division e.t.c.

In [6]:
x = "hello "
y = "world"
print(x + y) # this is string concatenation

hello world


In [ ]:
# Let's start by defining two integer variables
x = 5
y = 2

# the syntax for addition is very simple
z = x + y

# now z contains the sum of x and y
#print the results
print('Adding ' + str(x) +' and ' +str(y) + ' = ' + str(z))

# the above print command is a little restrictive when having multiple objects e.g. integers, floats, e.t.c,
# you need to convert all to strings and watch out for the spaces

# a more flexible print which automatically tries to convert objects to str
print('Adding', x, 'and', y, '=', z)

# we can alternative print with more flexibility
# even though you need to know the types of the variables is easier if you want to
# print something very long
# in the general case you can use %r and python will try to print it correctly
print('Adding %.2f and %.2f = %.2f'%(x,y,z))

# this will print a newline
print()

# alternatively we can put the newline character \n in the previous print
# we do this below


Adding 5 and 2 = 7
Adding 5 and 2 = 7
Adding 5.00 and 2.00 = 7.00



### **String Manipulation**:
---
We can perform various operations on strs in Python.
You'll mainly need it for printing or argument parsing, but it is useful to know the basics.

In [ ]:
# we can define a string
x = 'ml course'
print('Original string: %s\n'%x)

# and perform various manipulations
x += '2'
print('Original string after adding letter: %s\n'%x)

x += '_2019'
print('Original string after adding word: %s\n'%x)

# convert all to uppercase
print('Original string after converting to uppercase: %s\n'%x.upper())

# replace/remove whitespace
print('Original string after replacing whitespace with no space: %s\n'%x.replace(" ",""))

# access a substring
# take the first five letters
print('Get first five letters of the original string: %s\n'%x[0:5])

Original string: ml course

Original string after adding letter: ml course2

Original string after adding word: ml course2_2019

Original string after converting to uppercase: ML COURSE2_2019

Original string after replacing whitespace with no space: mlcourse2_2019

Get first five letters of the original string: ml co



In [9]:
# an alternative print format
x = 1
y = 2
z = x + y
print('{} {} {}'.format(x, y, z))


1 2 3


In [ ]:
# subtraction
z = x - y
print('Subtracting %.2f and %.2f = %.2f\n'%(x,y,z))

# Multiplication
z = x * y
print('Multiplying %.2f and %.2f = %.2f\n'%(x,y,z))

# division
z = x/y
print('Division of %.2f and %.2f = %.2f\n'%(x,y,z))

# modulo (see e.g. https://en.wikipedia.org/wiki/Modulo)
z = x % y
print('Modulo %.2f and %.2f = %.2f\n'%(x,y,z))

# integer division (see e.g. https://mathworld.wolfram.com/IntegerDivision.html)
z = x // y
print('Integer Division %d and %d = %d\n'%(x,y,z))

# power
z = x**2
print('Square %d = %d'%(x,z))

# square root
z = x**0.5
print('Sqrt %f = %f'%(x,z))

# unary operator

# x = x + 1
x += 1

# division
# x = x/2
x /= 2


Subtracting 5.00 and 2.00 = 3.00

Multiplying 5.00 and 2.00 = 10.00

Division of 5.00 and 2.00 = 2.50

Modulo 5.00 and 2.00 = 1.00

Integer Division 5 and 2 = 2

Square 5 = 25
Sqrt 5.000000 = 2.236068


### **Lists**:
---

In [10]:
# create a simple vector as a list
x = [0,1,4,5,6]

# print the vector and its length
print(x)
print(len(x))

# you can always get the type of an object (say x) by type(x)
print(type(x))

# lists in python can contain objects of different types
x = ['a', 1, '99', 5.,21, [2,4,5], -2.]
print(x)

# Indexing: access the elements
# if we want the first element
# python is zero based
print(x[0])

# the last element
print(x[-1])

#access a subset of the elements
# when we write 0:5, we take the 0,1,2,3,4 elements
print(x[0:5])

# we'll see some list manipulation after we introduce for loops

[0, 1, 4, 5, 6]
5
<class 'list'>
['a', 1, '99', 5.0, 21, [2, 4, 5], -2.0]
a
-2.0
['a', 1, '99', 5.0, 21]


### **Conditions and Indents**:
---
Python is a bit special when it comes to how we structure our code.

In Java, we had blocks of code, where we used brackets
{ } to denote the beggining and the end of a block.

In Python, we work with indents. The body/block of If statements, loops or function definitions must be indented for the compiler to know what is inside and what outside.

This is quite tricky in the beginning, but you get used to it very easily.

In [12]:
# contrary to other languages python dependes on indents (4 spaces or 1 Tab) to distinguish block of codes
#let's first define 2 variables for comparison
x = 2
y = 3

# compare and print which one is larger
if x > y:
  print('%d > %d'%(x, y))
else:
  print('%d < %d'%(x,y))

x = y = 2
# if we want to consider more cases, we use the elif keyword
if x>y:
  print('%d > %d' %(x,y))
elif x<y:
  print('%d < %d' %(x,y))
elif x == y:
  print('%d == %d' % (x,y))
else:
  raise ValueError('Something is seriously wrong.')

# the comparisons above essentially return a boolean value to check if the condition is true
z = True
if z: # you can write z == True but it is a bit redundant
  print('z is True')
else:
  print('z is False')

# you can use more conditions to construct a more complex dependency such as

# z is true and x>y is False so the falg below must be false
flag = z and x>y
print(flag)

# if one of the expressions is True, then the falg is True
flag = z or x > y
print(flag)

2 < 3
2 == 2
z is True
False
True


In [15]:
# we can also write one line if statements to define variables quickly
k = 5 if x == 2 else 4
print(k)

5


### **Loops in Python**:
___

In [16]:
# range() returns a sequence of integers
# one argument corresponds to the integer to stop to starting from zero
# thus in range(3) we'll have the sequence 0,1,2
# you can add a start integer and a step size range(1,5) will give 1,2,3,4
# and range(1,5,2) will give 1,3

print('Range(3):')
for i in range(3):
  # by using end = ' ' we wont get a newline after print, so we'll print inline
  print(i, end = ' ')

# if you replace end, do something like this to avoid printing the next command in the same line
print()

print('Range(1,5):')
for i in range(1,5):
  print(i, end = ' ')
print()

print('Range(1,5,2):')
for i in range(1,5,2):
  print(i, end = ' ')
print()

# while loop
steps = 100
# the loop will be performed 100 times
while steps > 0:
  steps -= 1

# you can break the loops if you want:
steps = 100

# while True will run forever if you don't break
while True:
  if steps == 50:
    break
  steps -= 1
print(steps)

# iterate the list
# we can use the for loops to access the elements of a list with indices
x = [0,1,4,5,6]

# len(X) returns the length of the list
print('Print each element in the list:')
for i in range(len(x)):
  print(x[i], end = ' ')

print()

# equivalently we can write
print('Equivalent print:')
for element in x:
  print(element, end = ' ')

print()

A = [[1,2,3], [4,5,6]]
print(len(A))
print(len(A[0]))

for i in range(len(A)):
  print(A[i])


Range(3):
0 1 2 
Range(1,5):
1 2 3 4 
Range(1,5,2):
1 3 
50
Print each element in the list:
0 1 4 5 6 
Equivalent print:
0 1 4 5 6 
2
3
[1, 2, 3]
[4, 5, 6]


In [17]:
steps = 100

# while True will run forever if you don't break
while True:
  if steps == 50:
    break
  steps -= 1
print(steps)


50


### **Functions**:
---


In [1]:
# Function definition
def add_function(x, y):
  return x + y

def multiply_function(x,y):
  return x * y

def greater(x,y):
  if x > y:
    return True
  else:
    return False

# if not specified, the value of y will be 0 (see below)
def greater_than(x, y=0):
  if x > y:
    return True
  else:
    return False

# call the function and assign result to new variable
z = add_function(2,3)
print(z)
z = multiply_function(2,3)
print(z)

x = 2
y = 20
x_greater_y = greater(x, y)
y_greater_x = greater(y, x)
print(x_greater_y)
print(y_greater_x)

x = -1
# with only one argument (that is x), y will have the default value 0
x_greater_0 = greater_than(x)
print(x_greater_0)

# however we can always specify both arguments
x_greater_minus_10 = greater_than(x, y = -10)
print(x_greater_minus_10)

5
6
False
True
False
True


### **NumPy**:

---


NumPy stands for Numerical Python and is a very powerful library for scientific computing with Python.

It provides all the necessary structures and interfaces for efficient and optimized computations.


In [33]:
# performing operation with lists is quite tedious
# let's say we have two lists
x = [1,2,3]
y = [4,5,6]

# we want to add them
# one would try
z = x + y

# however the syntax is a bit weird
print(z)

# what we get instead is a concatenation of the two lists
# if we want to add in native python we need to do it element by element

# not pythonic way
# create a new list
z = []

# iterate over all the items of the lists and add (assuming lists of the same size)
for i in range(len(x)):
  z.append(x[i] + y[i])

# now we get the sought result
print(z)

# a one liner for this computation
z = [x[i] + y[i] for i in range(len(x))]

print(z)

[1, 2, 3, 4, 5, 6]
[5, 7, 9]
[5, 7, 9]


In [34]:
# the problem gets worse for matrices (list of lists in Python)
# we can use numpy arrays for both lists and lists of lists
x_np = np.array(x)
y_np = np.array(y)
print('Numpy x :', x_np)
print('Numpy y :', y_np)

# now it is more intuitive to get the shape of the vector
print('Shape of np array:', x_np.shape)

# thus x_np is a vector with 3 elements
print(type(x_np))

# now addition is much easier
z = x_np + y_np
print('Adding the two np arrays results in:', z, 'with shape', z.shape, 'and type', type(z))

# numpy arrays in turn have their own type to know what elements it contains
print(z.dtype)

x = [1., 2., 3., 'd']
print(np.array(x).dtype)
print(np.array(x))

# create an array with a given shape
x = np.ones([2,5])

# create a matrix with random values
x_rand = np.random.random_sample([2,5])

y = np.ones([5,4])

# add scalar
z = x + 12.
print(z)

#subtract, multiply, division scalar
z = x - 9.
z = x / 12.
z = x * 20.


# add matrices
z = x + x_rand
print(z)

# you can use the matrix as a boolean condition.
# However you must define what exactly are you searching
# if you write an if statement with condition x > 0. you'll get an error
# use np.any(x>0) if you want the condition to be true even if only one value in x is larger than 0
# use np.all(x>0) if you want all values to be larger than 0 for the condition to be true
if np.all(x>0):
  print('True')

z = np.array([1,3,4,5])
if np.all(z >3):
  print('True') # not gonna happen
else:
  print('False')

# inf values
# we can use np.inf to set an inf value to either a scalar or an array

# power
z = x**2
print(z)
# or
z = np.power(x,2)
print(z)


print(x.shape)
print(x_rand.shape)
# multiplication
# matrices must be the same size
z = x * x_rand

# dot product
# remember if A.shape = [m, n], for the dot product of AB, we need B.shape = [n, k]
z = np.dot(x, y)

# sum
# you can sum all the values inside the array very easily
z = np.sum(x) # or z = x.sum()


# or you can do it by axis (rows/columns)
z = x.sum(0) # x has shape [2,5], z has shape [5]
z = x.sum(-1) # x has shape [2, 5], z has shape [2]

# you can also compute the mean this way
z = x.mean()
print('Overall mean: %.4f'%z)

z = x.mean(0)
print('Row mean: %s'%z)


z = x.mean(1)
print('Col mean: %s'%z)

# create a 5x5 indentity matrix
z = np.eye(5)
print(z)

# compute the trace of the matrix
print(np.trace(z))

Numpy x : [1 2 3]
Numpy y : [4 5 6]
Shape of np array: (3,)
<class 'numpy.ndarray'>
Adding the two np arrays results in: [5 7 9] with shape (3,) and type <class 'numpy.ndarray'>
int64
<U32
['1.0' '2.0' '3.0' 'd']
[[13. 13. 13. 13. 13.]
 [13. 13. 13. 13. 13.]]
[[1.47660132 1.82898659 1.06291941 1.58662486 1.63968811]
 [1.12783825 1.44212247 1.60337983 1.04292595 1.84867312]]
True
False
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)
(2, 5)
Overall mean: 1.0000
Row mean: [1. 1. 1. 1. 1.]
Col mean: [1. 1.]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
5.0
